[program:courra-sec]
command=/home/ubuntu/courra-sec/venv/bin/gunicorn app.main:app
        --bind 0.0.0.0:5000
        --worker-class eventlet
        --workers 1
        --timeout 120
        --log-level info
        --access-logfile /home/ubuntu/courra-sec/logs/access.log
        --error-logfile /home/ubuntu/courra-sec/logs/error.log
directory=/home/ubuntu/courra-sec
user=ubuntu
autostart=true
autorestart=true
startretries=5
stopasgroup=true
killasgroup=true
environment=FLASK_ENV="production"
stdout_logfile=/home/ubuntu/courra-sec/logs/courra-sec-out.log
stderr_logfile=/home/ubuntu/courra-sec/logs/courra-sec-err.log
